### ISSUE TITLE
Question about SWDIO/SWCLK on USB

### ISSUE THREAD

**Issue by ansemjo** [TobleMiner/ringlight#1]
As the title implies .. this isn't actually an issue but a question.

I scrolled through my GitHub dashboard, saw this project and opened up the project in KiCad ... that's when I saw that you routed SWDIO and SWCLK on the SBU lines of the USB receptacle.

At least it's not on D+/D-, I guess?
But I was wondering: is there a precendent for this? Is this okay? Is there a programming adapter using this exact wiring?

**Comment by TobleMiner** [comment]
No, as far as I'm aware this even violates the USB-C specification. I'd not recommend doing it in any design where the board is expected to be connected to a real USB port with actual DFP/UFP functionallity. I'll likely use it with USB-C power supplies only, thus I thought it might be interesting to try SWD on the SBU pins at least once.

**Comment by ansemjo** [comment]
I see. Too bad. Thanks!

> I'll likely use it with USB-C power supplies only, thus I thought it might be interesting to try SWD on the SBU pins at least once.

You'd need a cut-open cable or a breakout board for that though, correct? Or how do you plan to use it?

**Comment by TobleMiner** [comment]
I've some USB-C breakout boards (basically just hacked up boards from former projects) I'll use for SWD + Power.

**Comment by ansemjo** [comment]
FYI and as a reference for my future self: @alvarop posted a Twitter thread where they developed a "proper" way to do this using the Debug Accessory Mode.

https://mobile.twitter.com/alvaroprieto/status/1495860045728395278 ([archive](https://archive.vn/LXHXA))
